# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
rules:
  border-zero: 1
  brace-style:
    - 1
    -
      style: '1tbs'
  empty-line-between-blocks:
    - 1
    -
      allow-single-line-rulesets: false
  extends-before-declarations: 2
  extends-before-mixins: 2
  hex-length: 1
  hex-notation:
    - 1
    -
      style: uppercase
  indentation:
    - 1
    -
      size: 4
  leading-zero: 1
  mixin-name-format:
    - 1
    -
      allow-leading-underscore: false
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq
  nesting-depth:
    - 2
    -
      max-depth: 4
  no-color-keywords: 1
  no-debug: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-important: 1
  no-invalid-hex: 2
  no-mergeable-selectors:
    - 1
    -
      whitelist:
        - '50'
        - '100'
        - 'to'
        - 'from'
  no-misspelled-properties:
    - 1
    -
      'extra-properties':
        - 'osx-font-smoothing'
        - 'overflow-scrolling'
  no-trailing-zero: 1
  no-transition-all: 2
  no-warn: 1
  one-declaration-per-line: 1
  placeholder-in-extend: 2
  property-units: 2
  quotes:
    - 1
    -
      style: "double"
  url-quotes: 1
  shorthand-values: 1
  space-after-comma: 1
  space-after-colon: 1
  space-around-operator: 1
  space-before-colon: 1
  variable-name-format:
    - 1
    -
      allow-leading-underscore: false